/**
 * domains-us.js — US Listed Equities (NASDAQ, NYSE, S&P 500) Domain Map
 * Covers Magnificent 7, S&P 500 top components, Dow 30, and major US tech/fintech.
 */

export const US_KNOWN_DOMAINS = {
    // ── Magnificent 7 & Mega-Cap Tech ──
    'AAPL': { domain: 'apple.com', name: 'Apple Inc.' },
    'MSFT': { domain: 'microsoft.com', name: 'Microsoft Corporation' },
    'NVDA': { domain: 'nvidia.com', name: 'NVIDIA Corporation' },
    'GOOGL': { domain: 'google.com', name: 'Alphabet Inc. (Class A)' },
    'GOOG': { domain: 'google.com', name: 'Alphabet Inc. (Class C)' },
    'AMZN': { domain: 'amazon.com', name: 'Amazon.com Inc.' },
    'META': { domain: 'meta.com', name: 'Meta Platforms Inc.' },
    'TSLA': { domain: 'tesla.com', name: 'Tesla Inc.' },
    'AVGO': { domain: 'broadcom.com', name: 'Broadcom Inc.' },
    'ORCL': { domain: 'oracle.com', name: 'Oracle Corporation' },
    'CRM': { domain: 'salesforce.com', name: 'Salesforce Inc.' },
    'ADBE': { domain: 'adobe.com', name: 'Adobe Inc.' },
    'AMD': { domain: 'amd.com', name: 'Advanced Micro Devices Inc.' },
    'CSCO': { domain: 'cisco.com', name: 'Cisco Systems Inc.' },
    'INTC': { domain: 'intel.com', name: 'Intel Corporation' },
    'QCOM': { domain: 'qualcomm.com', name: 'QUALCOMM Inc.' },
    'TXN': { domain: 'ti.com', name: 'Texas Instruments Inc.' },
    'IBM': { domain: 'ibm.com', name: 'International Business Machines' },
    'NOW': { domain: 'servicenow.com', name: 'ServiceNow Inc.' },
    'INTU': { domain: 'intuit.com', name: 'Intuit Inc.' },
    'AMAT': { domain: 'appliedmaterials.com', name: 'Applied Materials Inc.' },
    'UBER': { domain: 'uber.com', name: 'Uber Technologies Inc.' },
    'ABNB': { domain: 'airbnb.com', name: 'Airbnb Inc.' },
    'COIN': { domain: 'coinbase.com', name: 'Coinbase Global Inc.' },
    'PLTR': { domain: 'palantir.com', name: 'Palantir Technologies Inc.' },
    'SHOP': { domain: 'shopify.com', name: 'Shopify Inc.' },
    'SPOT': { domain: 'spotify.com', name: 'Spotify Technology SA' },
    'SQ': { domain: 'block.xyz', name: 'Block Inc. (Square)' },
    'PYPL': { domain: 'paypal.com', name: 'PayPal Holdings Inc.' },
    'CRWD': { domain: 'crowdstrike.com', name: 'CrowdStrike Holdings Inc.' },
    'PANW': { domain: 'paloaltonetworks.com', name: 'Palo Alto Networks Inc.' },
    'SNOW': { domain: 'snowflake.com', name: 'Snowflake Inc.' },
    'NET': { domain: 'cloudflare.com', name: 'Cloudflare Inc.' },
    'ZS': { domain: 'zscaler.com', name: 'Zscaler Inc.' },
    'DASH': { domain: 'doordash.com', name: 'DoorDash Inc.' },
    'TEAM': { domain: 'atlassian.com', name: 'Atlassian Corporation' },
    'DDOG': { domain: 'datadoghq.com', name: 'Datadog Inc.' },
    'MDB': { domain: 'mongodb.com', name: 'MongoDB Inc.' },
    'DELL': { domain: 'dell.com', name: 'Dell Technologies Inc.' },
    'HPQ': { domain: 'hp.com', name: 'HP Inc.' },
    'HPE': { domain: 'hpe.com', name: 'Hewlett Packard Enterprise' },

    // ── Financials & Payments ──
    'BRK.A': { domain: 'berkshirehathaway.com', name: 'Berkshire Hathaway Inc. (Class A)' },
    'BRK.B': { domain: 'berkshirehathaway.com', name: 'Berkshire Hathaway Inc. (Class B)' },
    'BRK': { domain: 'berkshirehathaway.com', name: 'Berkshire Hathaway' },
    'JPM': { domain: 'jpmorganchase.com', name: 'JPMorgan Chase & Co.' },
    'V': { domain: 'visa.com', name: 'Visa Inc.' },
    'MA': { domain: 'mastercard.com', name: 'Mastercard Incorporated' },
    'BAC': { domain: 'bankofamerica.com', name: 'Bank of America Corporation' },
    'WFC': { domain: 'wellsfargo.com', name: 'Wells Fargo & Company' },
    'MS': { domain: 'morganstanley.com', name: 'Morgan Stanley' },
    'GS': { domain: 'goldmansachs.com', name: 'Goldman Sachs Group Inc.' },
    'BLK': { domain: 'blackrock.com', name: 'BlackRock Inc.' },
    'AXP': { domain: 'americanexpress.com', name: 'American Express Company' },
    'C': { domain: 'citigroup.com', name: 'Citigroup Inc.' },
    'SCHW': { domain: 'schwab.com', name: 'Charles Schwab Corporation' },
    'PGR': { domain: 'progressive.com', name: 'Progressive Corporation' },
    'CB': { domain: 'chubb.com', name: 'Chubb Limited' },
    'SPGI': { domain: 'spglobal.com', name: 'S&P Global Inc.' },
    'MCO': { domain: 'moodys.com', name: "Moody's Corporation" },
    'ICE': { domain: 'theice.com', name: 'Intercontinental Exchange Inc.' },
    'CME': { domain: 'cmegroup.com', name: 'CME Group Inc.' },
    'AON': { domain: 'aon.com', name: 'Aon plc' },
    'MMC': { domain: 'marshmclennan.com', name: 'Marsh & McLennan Companies' },

    // ── Healthcare & Pharmaceuticals ──
    'LLY': { domain: 'lilly.com', name: 'Eli Lilly and Company' },
    'UNH': { domain: 'unitedhealthgroup.com', name: 'UnitedHealth Group Incorporated' },
    'JNJ': { domain: 'jnj.com', name: 'Johnson & Johnson' },
    'ABBV': { domain: 'abbvie.com', name: 'AbbVie Inc.' },
    'MRK': { domain: 'merck.com', name: 'Merck & Co. Inc.' },
    'TMO': { domain: 'thermofisher.com', name: 'Thermo Fisher Scientific Inc.' },
    'ABT': { domain: 'abbott.com', name: 'Abbott Laboratories' },
    'PFE': { domain: 'pfizer.com', name: 'Pfizer Inc.' },
    'DHR': { domain: 'danaher.com', name: 'Danaher Corporation' },
    'BMY': { domain: 'bms.com', name: 'Bristol-Myers Squibb Company' },
    'AMGN': { domain: 'amgen.com', name: 'Amgen Inc.' },
    'ISRG': { domain: 'intuitive.com', name: 'Intuitive Surgical Inc.' },
    'CVS': { domain: 'cvshealth.com', name: 'CVS Health Corporation' },
    'GILD': { domain: 'gilead.com', name: 'Gilead Sciences Inc.' },
    'MDT': { domain: 'medtronic.com', name: 'Medtronic plc' },
    'SYK': { domain: 'stryker.com', name: 'Stryker Corporation' },
    'REGN': { domain: 'regeneron.com', name: 'Regeneron Pharmaceuticals Inc.' },
    'VRTX': { domain: 'vrtx.com', name: 'Vertex Pharmaceuticals Incorporated' },
    'ELV': { domain: 'elevancehealth.com', name: 'Elevance Health Inc.' },
    'CI': { domain: 'thecignagroup.com', name: 'The Cigna Group' },

    // ── Consumer Discretionary & Retail ──
    'WMT': { domain: 'walmart.com', name: 'Walmart Inc.' },
    'COST': { domain: 'costco.com', name: 'Costco Wholesale Corporation' },
    'HD': { domain: 'homedepot.com', name: 'The Home Depot Inc.' },
    'PG': { domain: 'pg.com', name: 'Procter & Gamble Company' },
    'KO': { domain: 'coca-colacompany.com', name: 'The Coca-Cola Company' },
    'PEP': { domain: 'pepsico.com', name: 'PepsiCo Inc.' },
    'NKE': { domain: 'nike.com', name: 'NIKE Inc.' },
    'MCD': { domain: 'mcdonalds.com', name: "McDonald's Corporation" },
    'SBUX': { domain: 'starbucks.com', name: 'Starbucks Corporation' },
    'MDLZ': { domain: 'mondelezinternational.com', name: 'Mondelez International Inc.' },
    'TGT': { domain: 'target.com', name: 'Target Corporation' },
    'LOW': { domain: 'lowes.com', name: "Lowe's Companies Inc." },
    'MO': { domain: 'altria.com', name: 'Altria Group Inc.' },
    'PM': { domain: 'pmi.com', name: 'Philip Morris International Inc.' },
    'CL': { domain: 'colgatepalmolive.com', name: 'Colgate-Palmolive Company' },
    'EL': { domain: 'elcompanies.com', name: 'The Estée Lauder Companies Inc.' },
    'TJX': { domain: 'tjx.com', name: 'The TJX Companies Inc.' },
    'BKNG': { domain: 'bookingholdings.com', name: 'Booking Holdings Inc.' },
    'LULU': { domain: 'lululemon.com', name: 'Lululemon Athletica Inc.' },

    // ── Industrials, Energy & Aerospace ──
    'XOM': { domain: 'exxonmobil.com', name: 'Exxon Mobil Corporation' },
    'CVX': { domain: 'chevron.com', name: 'Chevron Corporation' },
    'COP': { domain: 'conocophillips.com', name: 'ConocoPhillips' },
    'SLB': { domain: 'slb.com', name: 'Schlumberger Limited' },
    'EOG': { domain: 'eogresources.com', name: 'EOG Resources Inc.' },
    'GE': { domain: 'geaerospace.com', name: 'GE Aerospace' },
    'CAT': { domain: 'caterpillar.com', name: 'Caterpillar Inc.' },
    'BA': { domain: 'boeing.com', name: 'The Boeing Company' },
    'UNP': { domain: 'up.com', name: 'Union Pacific Corporation' },
    'HON': { domain: 'honeywell.com', name: 'Honeywell International Inc.' },
    'RTX': { domain: 'rtx.com', name: 'RTX Corporation' },
    'LMT': { domain: 'lockheedmartin.com', name: 'Lockheed Martin Corporation' },
    'DE': { domain: 'deere.com', name: 'Deere & Company' },
    'UPS': { domain: 'ups.com', name: 'United Parcel Service Inc.' },
    'FDX': { domain: 'fedex.com', name: 'FedEx Corporation' },
    'F': { domain: 'ford.com', name: 'Ford Motor Company' },
    'GM': { domain: 'gm.com', name: 'General Motors Company' },
    'WM': { domain: 'wm.com', name: 'Waste Management Inc.' },
    'ETN': { domain: 'eaton.com', name: 'Eaton Corporation plc' },
    'PH': { domain: 'parker.com', name: 'Parker-Hannifin Corporation' },

    // ── Media, Telecom & Entertainment ──
    'NFLX': { domain: 'netflix.com', name: 'Netflix Inc.' },
    'DIS': { domain: 'thewaltdisneycompany.com', name: 'The Walt Disney Company' },
    'CMCSA': { domain: 'comcastcorporation.com', name: 'Comcast Corporation' },
    'T': { domain: 'att.com', name: 'AT&T Inc.' },
    'VZ': { domain: 'verizon.com', name: 'Verizon Communications Inc.' },
    'TMUS': { domain: 't-mobile.com', name: 'T-Mobile US Inc.' },
    'WBD': { domain: 'wbd.com', name: 'Warner Bros. Discovery Inc.' },
    'EA': { domain: 'ea.com', name: 'Electronic Arts Inc.' },
    'TTWO': { domain: 'take2games.com', name: 'Take-Two Interactive Software' },
};
