/**
 * markets.js — Single source of truth for every country/market the catalog covers.
 * `scanner` is the TradingView scanner region; `suffix` is the Yahoo Finance ticker suffix
 * (empty = unknown / not applicable, link is then only a best-effort and Needs verification).
 * `dedupe` collapses the same company listed on many venues (e.g. Germany) into one logo.
 */
export const MARKETS = {
    us: { country: 'United States', scanner: 'america', suffix: '', exchanges: ['NASDAQ', 'NYSE'] },
    in: { country: 'India', scanner: 'india', suffix: '.NS', exchanges: ['NSE', 'BSE'] },
    uk: { country: 'United Kingdom', scanner: 'uk', suffix: '.L', exchanges: ['LSE'] },
    germany: { country: 'Germany', scanner: 'germany', suffix: '.DE', exchanges: ['XETRA'], dedupe: true, primary: ['XETR', 'FWB'] },
    france: { country: 'France', scanner: 'france', suffix: '.PA', exchanges: ['Euronext Paris'] },
    japan: { country: 'Japan', scanner: 'japan', suffix: '.T', exchanges: ['TSE'] },
    canada: { country: 'Canada', scanner: 'canada', suffix: '.TO', exchanges: ['TSX'] },
    australia: { country: 'Australia', scanner: 'australia', suffix: '.AX', exchanges: ['ASX'] },
    hongkong: { country: 'Hong Kong', scanner: 'hongkong', suffix: '.HK', exchanges: ['HKEX'] },
    korea: { country: 'South Korea', scanner: 'korea', suffix: '.KS', exchanges: ['KRX'] },
    taiwan: { country: 'Taiwan', scanner: 'taiwan', suffix: '.TW', exchanges: ['TWSE'] },
    china: { country: 'China', scanner: 'china', suffix: '.SS', exchanges: ['SSE', 'SZSE'] },
    brazil: { country: 'Brazil', scanner: 'brazil', suffix: '.SA', exchanges: ['B3'] },
    mexico: { country: 'Mexico', scanner: 'mexico', suffix: '.MX', exchanges: ['BMV'] },
    italy: { country: 'Italy', scanner: 'italy', suffix: '.MI', exchanges: ['Borsa Italiana'] },
    spain: { country: 'Spain', scanner: 'spain', suffix: '.MC', exchanges: ['BME'] },
    switzerland: { country: 'Switzerland', scanner: 'switzerland', suffix: '.SW', exchanges: ['SIX'] },
    netherlands: { country: 'Netherlands', scanner: 'netherlands', suffix: '.AS', exchanges: ['Euronext Amsterdam'] },
    sweden: { country: 'Sweden', scanner: 'sweden', suffix: '.ST', exchanges: ['Nasdaq Stockholm'] },
    norway: { country: 'Norway', scanner: 'norway', suffix: '.OL', exchanges: ['Oslo Bors'] },
    denmark: { country: 'Denmark', scanner: 'denmark', suffix: '.CO', exchanges: ['Nasdaq Copenhagen'] },
    finland: { country: 'Finland', scanner: 'finland', suffix: '.HE', exchanges: ['Nasdaq Helsinki'] },
    belgium: { country: 'Belgium', scanner: 'belgium', suffix: '.BR', exchanges: ['Euronext Brussels'] },
    austria: { country: 'Austria', scanner: 'austria', suffix: '.VI', exchanges: ['Wiener Boerse'], dedupe: true },
    portugal: { country: 'Portugal', scanner: 'portugal', suffix: '.LS', exchanges: ['Euronext Lisbon'] },
    ireland: { country: 'Ireland', scanner: 'ireland', suffix: '.IR', exchanges: ['Euronext Dublin'] },
    poland: { country: 'Poland', scanner: 'poland', suffix: '.WA', exchanges: ['GPW'] },
    turkey: { country: 'Turkey', scanner: 'turkey', suffix: '.IS', exchanges: ['BIST'] },
    israel: { country: 'Israel', scanner: 'israel', suffix: '.TA', exchanges: ['TASE'] },
    ksa: { country: 'Saudi Arabia', scanner: 'ksa', suffix: '.SR', exchanges: ['Tadawul'] },
    uae: { country: 'United Arab Emirates', scanner: 'uae', suffix: '', exchanges: ['ADX', 'DFM'] },
    qatar: { country: 'Qatar', scanner: 'qatar', suffix: '.QA', exchanges: ['QSE'] },
    kuwait: { country: 'Kuwait', scanner: 'kuwait', suffix: '.KW', exchanges: ['Boursa Kuwait'] },
    bahrain: { country: 'Bahrain', scanner: 'bahrain', suffix: '', exchanges: ['Bahrain Bourse'] },
    egypt: { country: 'Egypt', scanner: 'egypt', suffix: '.CA', exchanges: ['EGX'] },
    southafrica: { country: 'South Africa', scanner: 'rsa', suffix: '.JO', exchanges: ['JSE'] },
    nigeria: { country: 'Nigeria', scanner: 'nigeria', suffix: '', exchanges: ['NGX'] },
    kenya: { country: 'Kenya', scanner: 'kenya', suffix: '', exchanges: ['NSE Kenya'] },
    indonesia: { country: 'Indonesia', scanner: 'indonesia', suffix: '.JK', exchanges: ['IDX'] },
    malaysia: { country: 'Malaysia', scanner: 'malaysia', suffix: '.KL', exchanges: ['Bursa Malaysia'] },
    thailand: { country: 'Thailand', scanner: 'thailand', suffix: '.BK', exchanges: ['SET'] },
    singapore: { country: 'Singapore', scanner: 'singapore', suffix: '.SI', exchanges: ['SGX'] },
    philippines: { country: 'Philippines', scanner: 'philippines', suffix: '.PS', exchanges: ['PSE'] },
    vietnam: { country: 'Vietnam', scanner: 'vietnam', suffix: '', exchanges: ['HOSE', 'HNX'] },
    newzealand: { country: 'New Zealand', scanner: 'newzealand', suffix: '.NZ', exchanges: ['NZX'] },
    russia: { country: 'Russia', scanner: 'russia', suffix: '.ME', exchanges: ['MOEX'] },
    argentina: { country: 'Argentina', scanner: 'argentina', suffix: '.BA', exchanges: ['BYMA'] },
    chile: { country: 'Chile', scanner: 'chile', suffix: '.SN', exchanges: ['Santiago'] },
    colombia: { country: 'Colombia', scanner: 'colombia', suffix: '.CL', exchanges: ['BVC'] },
    peru: { country: 'Peru', scanner: 'peru', suffix: '', exchanges: ['BVL'] },
    greece: { country: 'Greece', scanner: 'greece', suffix: '.AT', exchanges: ['ATHEX'] },
    czech: { country: 'Czech Republic', scanner: 'czech', suffix: '.PR', exchanges: ['PSE Prague'] },
    hungary: { country: 'Hungary', scanner: 'hungary', suffix: '.BD', exchanges: ['BSE Budapest'] },
    romania: { country: 'Romania', scanner: 'romania', suffix: '.RO', exchanges: ['BVB'] },
    iceland: { country: 'Iceland', scanner: 'iceland', suffix: '.IC', exchanges: ['Nasdaq Iceland'] },
    estonia: { country: 'Estonia', scanner: 'estonia', suffix: '.TL', exchanges: ['Nasdaq Tallinn'] },
    latvia: { country: 'Latvia', scanner: 'latvia', suffix: '.RG', exchanges: ['Nasdaq Riga'] },
    lithuania: { country: 'Lithuania', scanner: 'lithuania', suffix: '.VS', exchanges: ['Nasdaq Vilnius'] },
    luxembourg: { country: 'Luxembourg', scanner: 'luxembourg', suffix: '', exchanges: ['LuxSE'] },
    cyprus: { country: 'Cyprus', scanner: 'cyprus', suffix: '', exchanges: ['CSE'] },
    srilanka: { country: 'Sri Lanka', scanner: 'srilanka', suffix: '', exchanges: ['CSE Colombo'] },
    pakistan: { country: 'Pakistan', scanner: 'pakistan', suffix: '.KA', exchanges: ['PSX'] },
    bangladesh: { country: 'Bangladesh', scanner: 'bangladesh', suffix: '', exchanges: ['DSE'] },
    morocco: { country: 'Morocco', scanner: 'morocco', suffix: '', exchanges: ['Casablanca'] },
    tunisia: { country: 'Tunisia', scanner: 'tunisia', suffix: '', exchanges: ['BVMT'] },
    serbia: { country: 'Serbia', scanner: 'serbia', suffix: '', exchanges: ['Belgrade'] },
    venezuela: { country: 'Venezuela', scanner: 'venezuela', suffix: '', exchanges: ['BVC Caracas'] },
    slovenia: { country: 'Slovenia', scanner: 'slovenia', suffix: '', exchanges: ['Ljubljana'] },
};
